// List des caractéristiques des equipements dufus (arme, coiffe, cape, etc...) avec leurs nom de rune associé exemple: point d'action (PA) = GA PA
export const effectsdata = [
    {
        dofusdb_id: 1,
        name: 'Point d\'action',
        rune_name: 'GA PA',
        density: 100,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_actionPoints.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78055.png',
    },
    {
        dofusdb_id: 23,
        name: 'Point de mouvement',
        rune_name: 'GA PME',
        density: 90,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_movementPoints.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78056.png',
    },
    {
        dofusdb_id: 19,
        name: 'Portée',
        rune_name: 'PO',
        density: 51,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_range.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78018.png',
    },
    {
        dofusdb_id: 11  ,
        name: 'Vitalité',
        rune_name: 'VI',
        density: 1,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_vitality.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78053.png',
        
    },
    {
        dofusdb_id: 14,
        name: 'Agilité',
        rune_name: 'AGE',
        density: 1,
        element: 'Air',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_air.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78047.png',
    },
    {
        dofusdb_id: 13,
        name: 'Chance',
        rune_name: 'CHA',
        density: 1,
        element: 'Eau',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_water.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78041.png',
    },
    {
        dofusdb_id: 10,
        name: 'Force',
        rune_name: 'FO',
        density: 1,
        element: 'Terre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_earth.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78044.png',
    },
    {
        dofusdb_id: 15,
        name: 'Intelligence',
        rune_name: 'INE',
        density: 1,
        element: 'Feu',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_fire.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78037.png',
    },
    {
        dofusdb_id: 25,
        name: 'Puissance',
        rune_name: 'PUI',
        density: 2,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_stamina.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78016.png',
    },
    {
        dofusdb_id: 18,
        name: 'Critique',
        rune_name: 'CRI',
        density: 10,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_crit.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78014.png',
    },
    {
        dofusdb_id: 12,
        name: 'Sagesse',
        rune_name: 'SA',
        density: 3,
        element: 'Neutre',
        categorie: 'CP',
        img: 'https://dofusdb.fr/icons/characteristics/tx_wisdom.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78050.png',
    },
    {
        dofusdb_id: 82,
        name: 'Retrait PA',
        rune_name: 'RET PA',
        density: 7,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_attackAP.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78087.png',
    },
    {
        dofusdb_id: 27,
        name: 'Esquive PA',
        rune_name: 'RE PA',
        density: 7,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_dodgeAP.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78083.png',
    },
    {
        dofusdb_id: 83,
        name: 'Retrait PM',
        rune_name: 'RET PME',
        density: 7,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_attackMP.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78089.png',
    },
    {
        dofusdb_id: 28,
        name: 'Esquive PM',
        rune_name: 'RE PME',
        density: 7,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_dodgeMP.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78085.png',
    },
    {
        dofusdb_id: 49,
        name: 'soin',
        rune_name: 'SO',
        density: 10,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_heal.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78013.png',
    },
    {
        dofusdb_id: 79,
        name: 'Tacle',
        rune_name: 'TAC',
        density: 4,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_tackle.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78077.png',
    },
    {
        dofusdb_id: 78,
        name: 'Fuite',
        rune_name: 'FUI',
        density: 4,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_escape.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78076.png',
    },
    {
        dofusdb_id: 44,
        name: 'initiative',
        rune_name: 'INI',
        density: 1,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_initiative.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78025.png',
    },
    {
        dofusdb_id: 26,
        name: 'invocation',
        rune_name: 'INV',
        density: 30,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_summonableCreaturesBoost.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78019.png',
    },
    {
        dofusdb_id: 48,
        name: 'prospection',
        rune_name: 'PROSPE',
        density: 3,
        element: 'Neutre', 
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_prospecting.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78036.png',
    },
    {
        dofusdb_id: 40,
        name: 'Pods',
        rune_name: 'POD',
        density: 1,
        element: 'Neutre',
        categorie: 'CS',
        img: 'https://dofusdb.fr/icons/characteristics/tx_pods.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78020.png',
    },
    {
        dofusdb_id: 16,
        name: 'Dommages',
        rune_name: 'DO',
        density: 20,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_damage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78015.png',
    },
    {
        dofusdb_id: 86,
        name: 'Dommages Critiques',
        rune_name: 'DO CRI',
        density: 5,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_criticalDamage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78073.png',
    },
    {
        dofusdb_id: 92,
        name: 'Dommages Neutre (Fixe)',
        rune_name: 'DO NEUTRE',
        density: 5,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_neutral.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78069.png',
    },
    {
        dofusdb_id: 88,
        name: 'Dommages Terre (Fixe)',
        rune_name: 'DO TERRE',
        density: 5,
        element: 'Terre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_earth.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78065.png',
    },
    {
        dofusdb_id: 89,
        name: 'Dommages Feu (Fixe)',
        rune_name: 'DO FEU',
        density: 5,
        element: 'Feu',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_fire.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78063.png',
    },
    {
        dofusdb_id: 90,
        name: 'Dommages Eau (Fixe)',
        rune_name: 'DO EAU',
        density: 5,
        element: 'Eau',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_water.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78061.png',
    },
    {
        dofusdb_id: 91,
        name: 'Dommages Air (Fixe)',
        rune_name: 'DO AIR',
        density: 5,
        element: 'Air',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_air.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78067.png',
    },
    {
        dofusdb_id: 50,
        name: 'Dommages Renvoi',
        rune_name: 'DO REN',
        density: 10,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_return.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78017.png',
    },
    {
        dofusdb_id: 70,
        name: 'Dommages Pièges (Fixe)',
        rune_name: 'DO PI',
        density: 5,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_trap.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78268.png',
    },
    {
        dofusdb_id: 69,
        name: 'Dommages Pièges (Puissance)',
        rune_name: 'PER PI',
        density: 2,
        element: 'Neutre',
        categorie: 'D',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78024.png',
    },
    {
        dofusdb_id: 84,
        name: 'Dommages Poussée',
        rune_name: 'DO POU',
        density: 5,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_push.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78081.png',
    },
    {
        dofusdb_id: 123,
        name: 'Dommages Sorts',
        rune_name: 'DO PER SO',
        density: 15,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_spellDamage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78094.png',
    },
    {
        dofusdb_id: 122,
        name: 'Dommages Armes',
        rune_name: 'DO PER AR',
        density: 15,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_weaponDamage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78093.png',
    },
    {
        dofusdb_id: 120,
        name: 'Dommages Distance',
        rune_name: 'DO PER DI',
        density: 15,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_distanceDamage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78091.png',
    },
    {
        dofusdb_id: 125,
        name: 'Dommages Mêlée',
        rune_name: 'DO PER ME',
        density: 15,
        element: 'Neutre',
        categorie: 'D',
        img: 'https://dofusdb.fr/icons/characteristics/tx_meleeDamage.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78092.png',
    },
    {
        dofusdb_id: 58,
        name: 'Resistance Neutre (Fixe)',
        rune_name: 'RE NEUTRE',
        density: 2,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_neutre.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78057.png',
    },
    {
        dofusdb_id: 37,
        name: 'Resistance Neutre (%)',
        rune_name: 'RE PER NEUTRE',
        density: 6,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_neutre.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78058.png',
    },
    {
        dofusdb_id: 54,
        name: 'Resistance Terre (Fixe)',
        rune_name: 'RE TERRE',
        density: 2,
        element: 'Terre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_strength.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78034.png',
    },
    {
        dofusdb_id: 33,
        name: 'Resistance Terre (%)',
        rune_name: 'RE PER TERRE',
        density: 6,
        element: 'Terre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_strength.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78035.png',
    },
    {
        dofusdb_id: 55,
        name: 'Resistance Feu (Fixe)',
        rune_name: 'RE FEU',
        density: 2,
        element: 'Feu',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_intelligence.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78028.png',
    },
    {
        dofusdb_id: 34,
        name: 'Resistance Feu (%)',
        rune_name: 'RE PER FEU',
        density: 6,
        element: 'Feu',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_intelligence.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78029.png',
    },
    {
        dofusdb_id: 56,
        name: 'Resistance Eau (Fixe)',
        rune_name: 'RE EAU',
        density: 2,
        element: 'Eau',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_chance.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78030.png',
    },
    {
        dofusdb_id: 35,
        name: 'Resistance Eau (%)',
        rune_name: 'RE PER EAU',
        density: 6,
        element: 'Eau',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_chance.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78031.png',
    },
    {
        dofusdb_id: 57,
        name: 'Resistance Air (Fixe)',
        rune_name: 'RE AIR',
        density: 2,
        element: 'Air',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_agility.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78032.png',
    },
    {
        dofusdb_id: 36,
        name: 'Resistance Air (%)',
        rune_name: 'RE PER AIR',
        density: 6,
        element: 'Air',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_agility.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78033.png',
    },
    {
        dofusdb_id: 87,
        name: 'Resistance Critiques (Fixe)',
        rune_name: 'RE CRI',
        density: 2,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_criticalReduction.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78071.png',
    },
    {
        dofusdb_id: 85,
        name: 'Resistance Poussée (Fixe)',
        rune_name: 'RE POU',
        density: 2,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_pushReduction.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78079.png',
    },
    {
        dofusdb_id: 121,
        name: 'Resistance Distance',
        rune_name: 'RE PER DI',
        density: 15,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_distance.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78079.png',
    },
    {
        dofusdb_id: 124,
        name: 'Resistance Melee',
        rune_name: 'RE PER ME',
        density: 15,
        element: 'Neutre',
        categorie: 'R',
        img: 'https://dofusdb.fr/icons/characteristics/tx_res_melee.png',
        rune_img: 'https://static.ankama.com/dofus/www/game/items/200/78095.png',
    },

]